server {
    listen 443 ssl;
    server_name 10.50.58.11;

    ssl_certificate /etc/nginx/certs/rugby.crt;
    ssl_certificate_key /etc/nginx/certs/rugby.key;

    # Cabeceras de Seguridad OWASP
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net; img-src 'self' data:; connect-src 'self' https://10.50.58.11 https://cdn.jsdelivr.net;" always;
    add_header X-Frame-Options "DENY" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    # 1. Entrega del Frontend
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # 2. Proxy Maestro para la API
    # Esto enviará /api/register, /api/token y /api/jugadores al backend
    location /api/ {
        proxy_pass http://api:8000; 
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
